

class Pasa{
  String fromdoortodoor = "จากประตูร้าน สู่ประตูบ้าน",
  store = "ร้านค้า ",
  howtouse = "การใช้งาน ",
  becomeourpartner = "ร่วมงานกับเรา",
  about = "เกี่ยวกับ",
  login = "ล็อกอิน",
  register = "สมัครสมาชิก",
  email = "อีเมล์",
  password = "พาสเวิร์ด",
  forgotpassword = "ลืมรหัสผ่าน",
  firstname = "ชื่อ",
  lastname = "นามสกุล",
  tel = "เบอร์โทรศัพท์",
  submit = "ส่ง",
  welcome = "ยินดีต้อนรับ",
  userinformation = "ข้อมูลส่วนตัว ",
  logout = "ออกจากระบบ",
  resteruant = "ร้านค้า",
  categories = "หมวดหมู่ยอดนิยม",
  promotion = "โปรโมชั่น ",
  averagecost = "ราคาโดยประมาณ",
  Recommended = "เมนูแนะนำประจำร้าน",
  Recommended_desc = "เมนูแนะนำสุดฮอตที่ต้องกลับมาสั่งใหม่ ",
  hot = "ฮอต",
  nowopen = "เปิดแล้ว",
  cmaincourse = "เมนูหลัก",
  sidedish = "ของทานเล่น",
  vegan = "มังสวิรัติ",
  veganwrap = "แวร็ปมังสวิรัติ",
  vegetarianwraps = "แวร็ปเจ",
  chickenorporkwraps = "แวร็ปหมูไก่",
  drinks = "เครื่องดื่ม",
  basket = "ตระกร้าสินค้า",
  list = "รายการ",
  amount = "จำนวน",
  gift = "แถม",
  total = "รวมทั้งหมด ",
  clear = "ล้างตะกร้า",
  placeorder = "ยืนยันการสั่งซื้อ",
  nextround = "รอบถัดไป ",
  itemsinbasket = "รายการในตะกร้า ",
  items = "รายการ ",
  addtobasket = "เพิ่มในรถเข็น",
  howitworks = "การใช้งาน",
  browse = "ค้นหา",
  browse_desc = "ค้นหาร้านอาหารที่อยู่บริเวณนี้ใกล้เคียงท่านพร้อมกับเลือกร้านอาหารต่างๆไม่ว่าจะเป็นร้านอาหารตามสั่งริมทางจนไปถึงร้านอาหารแบรนด์ดังที่มีเมนูที่ท่านชื่นชอบ",
  choosesyourdishes = "เลือกเมนูที่ชื่นชอบ ",
  choosesyourdishes_desc = "เลือกเมนูอาหารเมนูเครื่องดื่มต่างๆจากร้านที่คุณชื่นชอบและทั้งยังสามารถเลือกเวลาการจัดส่งอาหารตามที่ต้องการและระบุสถานที่ที่ต้องให้ไปส่งโดยระบุลงในแผนที่",
  confrimorderandpay = "ยืนยันออเดอร์และชำระเงิน",
  confrimorderandpay_desc = "เมื่อท่านยืนยันออเดอร์แล้วท่านสามารถเลือกชำระเป็นเงินสดหรือท่านจะชำระด้วยการโอนทั้ง 2 วิธีนี้ท่านสามารถเลือกการชำระเงินได้อย่างสะดวกสบาย",
  deliveryorpickup = "จัดส่งถึงที่หรือรับเองที่ร้าน",
  deliveryorpickup_desc = "เรามีบริการจัดส่งถึงที่และมีสถานะขั้นตอนการดำเนินการตั้งแต่รับออเดอร์อาหารจนถึงมือท่านหรือท่านสามารถรับอาหารเองที่ร้านได้ตามที่ท่านสะดวกเดินทางมารับ",
  beourpartner = "ร่วมงานกับเรา",
  whyus = "ทำไมต้องเลือกเรา",
  whyus_desc = "เราคือแพลตฟอร์มสั่งอาหารออนไลน์ที่รวบรวมร้านอาหารต่างๆที่ให้บริการเดลิเวอรี่หรือรับเองที่ร้านเราเริ่มให้บริการในพื้นที่จังหวัดเชียงใหม่เป็นแห่งแรกดำเนินธุรกิจโดยคนเชียงใหม่เพื่อคนเชียงใหม่",
  increseslaes = "เพิ่มยอดขายให้ร้านค้า",
  increseslaes_desc = "ร้านอาหารของท่านจะเข้าถึงลูกค้านับล้านคนเพราะลูกค้าของเราค้นหาร้านอาหารใหม่ๆอร่อยๆเพิ่มขึ้นทุกวันเป็นอีกกลยุทธ์หนึ่งที่ช่วยเพิ่มยอดขายให้กับร้านค้าของท่าน",
  easytomanagethestore = "จัดระบบร้านค้าได้ด้วยตัวเอง",
  easytomanagethestore_desc = "รับคำสั่งซื้อจากลูกค้าบนเว็บไซต์และยังสามารถเปิดปิดร้านได้เองอีกทั้งยังสามารถเพิ่มเมนูอาหารของร้านได้ไม่ยุ่งยากและสามารถตรวจสอบยอดขายได้ทุกวัน",
  about_desc = "จากประตูร้านสู่ประตูบ้านซอฟต์แวร์แพลตฟอร์มรูปแบบที่แตกต่างสามารถช่วยให้คุณค้นหาร้านโปรดปรานและนำส่งเมนูสุดโปรดของคุณถึงประตูบ้านได้อย่างง่ายดายพร้อมเลือกรอบเวลาในการจัดส่งก่อนถึงมื้อสำคัญ",
  form = "จาก",
  address = "ที่อยู่",
  to = "ส่งไปที่",
  previous = "ที่อยู่ปัจจุบัน",
  edit = "แก้ไข",
  immediatedelivery = "จัดส่งทันที",
  ordersummary = "สรุปคำสั่งซื้อ ",
  manageoptions = "จัดการตัวเลือก",
  note = "หมายเหตุ",
  addmorecomment = "ข้อเสนอแนะเพิ่มเติม",
  save = "บันทึก",
  foodfees = "ค่าอาหาร",
  deliveryfee = "ค่าจัดส่ง",
  calculatingdistance = "กำลังคำนวณระยะทาง",
  specialinstructions = "ข้อเสนอแนะ",
  paymentmethod = "วิธีการชำระ",
  cash = "เงินสด",
  banking = "พร้อมเพย์ / โอนเงิน",
  orderinprocess = "รายการที่กำลังดำเนินการ ",
  orderhistory = "ประวัติการสั่งซื้อ",
  time = "เวลา",
  price = "ราคา",
  status = "สถานะ",
  storeacceptingitems = "ร้านค้าตอบรับรายการ",
  yourbasketisempty = "ไม่มีสินค้าในตะกร้า",
  noitemalert = "กรุณาเลือกสินค้าก่อนทำรายการต่อไปค่ะ ",
  nolocatealert = "ไม่สามารถรับที่อยู่ปัจจุบันของท่านได้",
  nolocatealert_desc = "โปรดอนุญาตให้บราวเซอร์เข้าถึงที่อยู่ของท่านค่ะ ",
  closed = "ร้านปิด",
  editlist = "แก้ไขรายการ",
  tracking = "ติดตามการจัดส่ง",
  cartlist = "รายการสินค้า",
  paybycash = "ชำระด้วยเงินสด",
  deliveryDetail = "รายละเอียดการจัดส่ง",
  backHome = "กลับหน้าแรก",
  outofservice = "นอกพื้นที่ให้บริการ",
  chooseloc = "เลือกตำแหน่ง",
  addommment = "รายละเอียดเพิ่มเติ่ม",
  commment = "หมายเหตุ";
setPasa(String pasa){

  if(pasa == 'ภาษาไทย'){
    this.fromdoortodoor = "จากประตูร้าน สู่ประตูบ้าน" ;
    this.store = "ร้านค้า " ;
    this.howtouse = "การใช้งาน " ;
    this.becomeourpartner = "ร่วมงานกับเรา" ;
    this.about = "เกี่ยวกับ" ;
    this.login = "ล็อกอิน" ;
    this.register = "สมัครสมาชิก" ;
    this.email = "อีเมล์" ;
    this.password = "พาสเวิร์ด" ;
    this.forgotpassword = "ลืมรหัสผ่าน" ;
    this.firstname = "ชื่อ" ;
    this.lastname = "นามสกุล" ;
    this.tel = "เบอร์โทรศัพท์" ;
    this.submit = "ส่ง" ;
    this.welcome = "ยินดีต้อนรับ" ;
    this.userinformation = "ข้อมูลส่วนตัว " ;
    this.logout = "ออกจากระบบ" ;
    this.resteruant = "ร้านค้า" ;
    this.categories = "หมวดหมู่ยอดนิยม" ;
    this.promotion = "โปรโมชั่น " ;
    this.averagecost = "ราคาโดยประมาณ" ;
    this.Recommended = "เมนูแนะนำประจำร้าน" ;
    this.Recommended_desc = "เมนูแนะนำสุดฮอตที่ต้องกลับมาสั่งใหม่ " ;
    this.hot = "ฮอต" ;
    this.nowopen = "เปิดแล้ว" ;
    this.cmaincourse = "เมนูหลัก" ;
    this.sidedish = "ของทานเล่น" ;
    this.vegan = "มังสวิรัติ" ;
    this.veganwrap = "แวร็ปมังสวิรัติ" ;
    this.vegetarianwraps = "แวร็ปเจ" ;
    this.chickenorporkwraps = "แวร็ปหมูไก่" ;
    this.drinks = "เครื่องดื่ม" ;
    this.basket = "ตระกร้าสินค้า" ;
    this.list = "รายการ" ;
    this.amount = "จำนวน" ;
    this.gift = "แถม" ;
    this.total = "รวมทั้งหมด " ;
    this.clear = "ล้างตะกร้า" ;
    this.placeorder = "ยืนยันการสั่งซื้อ" ;
    this.nextround = "รอบถัดไป " ;
    this.itemsinbasket = "รายการในตะกร้า " ;
    this.items = "รายการ " ;
    this.addtobasket = "เพิ่มในรถเข็น" ;
    this.howitworks = "การใช้งาน" ;
    this.browse = "ค้นหา" ;
    this.browse_desc = "ค้นหาร้านอาหารที่อยู่บริเวณนี้ใกล้เคียงท่านพร้อมกับเลือกร้านอาหารต่างๆไม่ว่าจะเป็นร้านอาหารตามสั่งริมทางจนไปถึงร้านอาหารแบรนด์ดังที่มีเมนูที่ท่านชื่นชอบ" ;
    this.choosesyourdishes = "เลือกเมนูที่ชื่นชอบ " ;
    this.choosesyourdishes_desc = "เลือกเมนูอาหารเมนูเครื่องดื่มต่างๆจากร้านที่คุณชื่นชอบและทั้งยังสามารถเลือกเวลาการจัดส่งอาหารตามที่ต้องการและระบุสถานที่ที่ต้องให้ไปส่งโดยระบุลงในแผนที่" ;
    this.confrimorderandpay = "ยืนยันออเดอร์และชำระเงิน" ;
    this.confrimorderandpay_desc = "เมื่อท่านยืนยันออเดอร์แล้วท่านสามารถเลือกชำระเป็นเงินสดหรือท่านจะชำระด้วยการโอนทั้ง 2 วิธีนี้ท่านสามารถเลือกการชำระเงินได้อย่างสะดวกสบาย" ;
    this.deliveryorpickup = "จัดส่งถึงที่หรือรับเองที่ร้าน" ;
    this.deliveryorpickup_desc = "เรามีบริการจัดส่งถึงที่และมีสถานะขั้นตอนการดำเนินการตั้งแต่รับออเดอร์อาหารจนถึงมือท่านหรือท่านสามารถรับอาหารเองที่ร้านได้ตามที่ท่านสะดวกเดินทางมารับ" ;
    this.beourpartner = "ร่วมงานกับเรา" ;
    this.whyus = "ทำไมต้องเลือกเรา" ;
    this.whyus_desc = "เราคือแพลตฟอร์มสั่งอาหารออนไลน์ที่รวบรวมร้านอาหารต่างๆที่ให้บริการเดลิเวอรี่หรือรับเองที่ร้านเราเริ่มให้บริการในพื้นที่จังหวัดเชียงใหม่เป็นแห่งแรกดำเนินธุรกิจโดยคนเชียงใหม่เพื่อคนเชียงใหม่" ;
    this.increseslaes = "เพิ่มยอดขายให้ร้านค้า" ;
    this.increseslaes_desc = "ร้านอาหารของท่านจะเข้าถึงลูกค้านับล้านคนเพราะลูกค้าของเราค้นหาร้านอาหารใหม่ๆอร่อยๆเพิ่มขึ้นทุกวันเป็นอีกกลยุทธ์หนึ่งที่ช่วยเพิ่มยอดขายให้กับร้านค้าของท่าน" ;
    this.easytomanagethestore = "จัดระบบร้านค้าได้ด้วยตัวเอง" ;
    this.easytomanagethestore_desc = "รับคำสั่งซื้อจากลูกค้าบนเว็บไซต์และยังสามารถเปิดปิดร้านได้เองอีกทั้งยังสามารถเพิ่มเมนูอาหารของร้านได้ไม่ยุ่งยากและสามารถตรวจสอบยอดขายได้ทุกวัน" ;
    this.about_desc = "จากประตูร้านสู่ประตูบ้านซอฟต์แวร์แพลตฟอร์มรูปแบบที่แตกต่างสามารถช่วยให้คุณค้นหาร้านโปรดปรานและนำส่งเมนูสุดโปรดของคุณถึงประตูบ้านได้อย่างง่ายดายพร้อมเลือกรอบเวลาในการจัดส่งก่อนถึงมื้อสำคัญ" ;
    this.form = "จาก" ;
    this.address = "ที่อยู่" ;
    this.to = "ส่งไปที่" ;
    this.previous = "ที่อยู่ปัจจุบัน" ;
    this.edit = "แก้ไข" ;
    this.immediatedelivery = "จัดส่งทันที" ;
    this.ordersummary = "สรุปคำสั่งซื้อ " ;
    this.manageoptions = "จัดการตัวเลือก" ;
    this.note = "หมายเหตุ" ;
    this.addmorecomment = "ข้อเสนอแนะเพิ่มเติม" ;
    this.save = "บันทึก" ;
    this.foodfees = "ค่าอาหาร" ;
    this.deliveryfee = "ค่าจัดส่ง" ;
    this.calculatingdistance = "กำลังคำนวณระยะทาง" ;
    this.specialinstructions = "ข้อเสนอแนะ" ;
    this.paymentmethod = "วิธีการชำระ" ;
    this.cash = "เงินสด" ;
    this.banking = "พร้อมเพย์ / โอนเงิน" ;
    this.orderinprocess = "รายการที่กำลังดำเนินการ " ;
    this.orderhistory = "ประวัติการสั่งซื้อ" ;
    this.time = "เวลา" ;
    this.price = "ราคา" ;
    this.status = "สถานะ" ;
    this.storeacceptingitems = "ร้านค้าตอบรับรายการ" ;
    this.yourbasketisempty = "ไม่มีสินค้าในตะกร้า" ;
    this.noitemalert = "กรุณาเลือกสินค้าก่อนทำรายการต่อไปค่ะ " ;
    this.nolocatealert = "ไม่สามารถรับที่อยู่ปัจจุบันของท่านได้" ;
    this.nolocatealert_desc = "โปรดอนุญาตให้บราวเซอร์เข้าถึงที่อยู่ของท่านค่ะ " ;
    this.closed = "ร้านปิด" ;
    this.editlist = "แก้ไขรายการ" ;
    this.tracking = "ติดตามการจัดส่ง" ;
    this.cartlist = "รายการสินค้า" ;
    this.paybycash = "ชำระด้วยเงินสด" ;
    this.deliveryDetail = "รายละเอียดการจัดส่ง" ;
    this.backHome = "กลับหน้าแรก" ;
    this.outofservice = "นอกพื้นที่ให้บริการ" ;
    this.chooseloc = "เลือกตำแหน่ง" ;
    this.addommment = "รายละเอียดเพิ่มเติ่ม" ;
    this.commment = "หมายเหตุ";
  }else if(pasa == 'English'){
    this.fromdoortodoor = "From Door To Door";
    this.store = "Store";
    this.howtouse = "How To Use";
    this.becomeourpartner = "Become Our Partner";
    this.about = "About";
    this.login = "Log In";
    this.register = "Register";
    this.email = "E mail";
    this.password = "Password";
    this.forgotpassword = "Forgot Password";
    this.firstname = "First Name";
    this.lastname = "Last Name";
    this.tel = "Tel. Number";
    this.submit = "Submit";
    this.welcome = "Welcome";
    this.userinformation = "Information";
    this.logout = "Log Out";
    this.resteruant = "Resteruant";
    this.categories = "Categories";
    this.promotion = "Promotion";
    this.averagecost = "Average Cost";
    this.Recommended = "Recommended";
    this.Recommended_desc = "Recommend You The Best Expreience";
    this.hot = "HOT";
    this.nowopen = "BEST Seller";
    this.cmaincourse = "Main Course";
    this.sidedish = "Side Dish";
    this.vegan = "Ve Gan";
    this.veganwrap = "Vegan Wrap";
    this.vegetarianwraps = "Vegetarian Wraps";
    this.chickenorporkwraps = "Chicken Or Pork Wraps";
    this.drinks = "Drinks";
    this.basket = "Bas Ket";
    this.list = "List";
    this.amount = "Amount";
    this.promotion = "Pro Motion";
    this.gift = "Gift";
    this.total = "Total";
    this.clear = "Clear";
    this.placeorder = "Place Order";
    this.nowopen = "Now Open";
    this.nextround = "Next Round";
    this.itemsinbasket = "Items In Basket";
    this.items = "Items";
    this.addtobasket = "Add To Basket";
    this.howitworks = "How It Works ";
    this.browse = "Browse";
    this.browse_desc = "Search For Hundreds Of Restaurants Around You From Street Foods To Well-Known Resteruant To Get Your Favorite Cuisine";
    this.choosesyourdishes = "Chooses Your Dishes";
    this.choosesyourdishes_desc = "Choose Foods And Drinks That You Like Then Choose Time And Location For Delivery";
    this.confrimorderandpay = "Confrim Order And Pay";
    this.confrimorderandpay_desc = "After The Order Is Confrimed Costumer Can Choose Two Method Of Paying By Cash Or By Tranfer Money";
    this.deliveryorpickup = "Delivery Or Pick Up By Your Own";
    this.deliveryorpickup_desc = "We Offer Delivery Service That Cutomer Could Track  Progress And The Condition Of Your Order Or Else Cutomer Could Choose To Pick The Food Up At The Resteruant";
    this.beourpartner = "Be Our Partner";
    this.whyus = "Why Us";
    this.whyus_desc = "Is Online Food Delivery Platform That Gather Resteruant That Customer Could Order Food To Delivery Or Pick Up Food We Frist Choose To Service Chiang Mai Is Fromed By People In Chiang Mai For Chiang Mai People.";
    this.increseslaes = "Increse Slaes";
    this.increseslaes_desc = "Your Resteruant Will Bee Seeen By Miilions Of Customer And Our Customer Will Always Find For New Resteruant It Is Another Way To Increase Sales";
    this.easytomanagethestore = "Easy To Self Manage The Store";
    this.easytomanagethestore_desc = "Can Self Receive Customer Order From Webpage Open A Close Restaurant Add Manage Menu And Can Check For Income Everyday";
    this.about_desc = "From Door To Door Is An Solfware Platform That Can Help You To Find Your Favorite Dishes From Your Favrite Resteraunt Can Aslo Arrange The Devilery Time Before Your Special Meals";
    this.form = "From";
    this.address = "Address";
    this.to = "To";
    this.previous = "Your location";
    this.edit = "Edit";
    this.nextround = "Next Round";
    this.immediatedelivery = "Immediate Delivery";
    this.ordersummary = "Order Summary";
    this.manageoptions = "Manage Options";
    this.note = "Note";
    this.addmorecomment = "You Can Add More Information Here";
    this.save = "Save";
    this.foodfees = "Food Fees";
    this.deliveryfee = "Delivery Fee";
    this.calculatingdistance = "Calculating Distance";
    this.specialinstructions = "Special Instructions";
    this.paymentmethod = "Payment Method";
    this.cash = "Cash";
    this.banking = "Banking";
    this.placeorder = "Place Order";
    this.orderinprocess = "Order In Process";
    this.orderhistory = "Order History";
    this.time = "Time";
    this.list = "List";
    this.amount = "Amount";
    this.price = "Price";
    this.status = "Status";
    this.storeacceptingitems = "Store Accepting Items";
    this.yourbasketisempty = "Your Basket Is Empty";
    this.noitemalert = "Please Add Items  Before Continuing The Transaction";
    this.nolocatealert = "Unable To Receive Your Current Address";
    this.nolocatealert_desc = "Browser Would Like To Use Your Current Location";
    this.closed = "Closed";
    this.editlist = "Edit Shipping";
    this.tracking = "Tracking Your Order";
    this.cartlist = "Shipping List";
    this.paybycash = "Pay by Cash";
    this.deliveryDetail = "Delivery Detail";
    this.backHome = "Back To Homepage";
    this.outofservice = "Out of service";
    this.chooseloc = "Location Marker";
    this.addommment = "Addition Commment";
    this.commment = "Commment";
  }
  else if(pasa == ' 简体中文'){
    this.fromdoortodoor= "从店门到家门";
    this.store= "商家";
    this.howtouse= "使用方法";
    this.becomeourpartner= "入驻加盟";
    this.about= "关于";
    this.login= "登入";
    this.register= "注册账号";
    this.email= "邮箱";
    this.password= "密码";
    this.forgotpassword= "忘记密码";
    this.firstname= "名";
    this.lastname= "姓";
    this.tel= "电话号码";
    this.submit= "上传";
    this.welcome= "欢迎";
    this.userinformation= "用户信息";
    this.logout= "登出";
    this.resteruant= "商家";
    this.categories= "食物类别";
    this.promotion= "优惠活动";
    this.averagecost= "平均用餐费";
    this.Recommended= "商家推荐";
    this.Recommended_desc= "把最热门的菜推荐给您";
    this.hot= "热销";
    this.nowopen= "正在营业";
    this.cmaincourse= "主食";
    this.sidedish= "小吃";
    this.vegan= "素食品";
    this.veganwrap= "全素卷";
    this.vegetarianwraps= "蛋奶素卷";
    this.chickenorporkwraps= "猪鸡肉卷";
    this.drinks= "饮料";
    this.basket= "购物篮";
    this.list= "菜品";
    this.amount= "份数";
    this.promotion= "优惠活动";
    this.gift= "赠送";
    this.total= "总计";
    this.clear= "清空";
    this.placeorder= "确认下单";
    this.nowopen= "正在营业";
    this.nextround= "下一班车";
    this.itemsinbasket= "购物篮里有";
    this.items= "份量";
    this.addtobasket= "添加到购物篮";
    this.howitworks= "使用方法";
    this.browse= "搜索";
    this.browse_desc= "搜索附近的餐厅从路边小吃到有名气的餐厅任何饮食让您选";
    this.choosesyourdishes= "选择喜欢的食品";
    this.choosesyourdishes_desc= "从您喜欢的店选上您合心食物以及饮料可选发送时间以及收餐地点";
    this.confrimorderandpay= "确认订单和支付";
    this.confrimorderandpay_desc= "确认订单之后可选现金支付或汇款支付等两种支付方法";
    this.deliveryorpickup= "外卖或自取";
    this.deliveryorpickup_desc= "我们提供外卖服务客户可追踪食物的发送状态 或客户能选到店里自取";
    this.beourpartner= "入驻加盟";
    this.whyus= "为什么选择我们";
    this.whyus_desc= "是个聚集餐厅网上订餐平台可选择外卖和自取功能首选给清迈服务创业于清迈人为清迈人服务";
    this.increseslaes= "增加销售量";
    this.increseslaes_desc= "您的店将会被成千上万的客户眼中看见我们的客户会不停的寻找新的餐厅为了增加您的销量的策略";
    this.easytomanagethestore= "可以自己操作店面";
    this.easytomanagethestore_desc= "客户接单开-关店在店面上添加菜品以及查看每日销售额都可以轻松搞定";
    this.about_desc= "从店门到家门是一个与众不同的软件平台能协助您找到您心中的餐厅以及把您最喜欢的菜送到家前可在到重要聚餐之前选定发送时间";
    this.form= "从";
    this.address= "地址";
    this.to= "到";
    this.previous= "目前的地址";
    this.edit= "编辑";
    this.nextround= "车班";
    this.immediatedelivery= "马上发送";
    this.ordersummary= "订单总结";
    this.manageoptions= "食物要求";
    this.note= "备注";
    this.addmorecomment= "请输入更多信息";
    this.save= "保存";
    this.foodfees= "食物费";
    this.deliveryfee= "配送费";
    this.calculatingdistance= "正在计算路程";
    this.specialinstructions= "评价";
    this.paymentmethod= "支付方式";
    this.cash= "现金";
    this.placeorder= "确认订餐";
    this.orderinprocess= "正在进行";
    this.orderhistory= "订餐记录";
    this.time= "时间";
    this.list= "菜品";
    this.amount= "份量";
    this.price= "品类";
    this.status= "状态";
    this.storeacceptingitems= "商家已收到";
    this.yourbasketisempty= "购物篮里没有食品";
    this.noitemalert= "请选择产品";
    this.nolocatealert= "网站无法确定您的位置";
    this.nolocatealert_desc= "允许网站知道您所在的位置";
    this.closed= "關閉";
    this.editlist= "编辑";
    this.cartlist= "份量";
    this.paybycash= "现金";
    this.deliveryDetail= "詳情";
    this.backHome= "主頁";
    this.outofservice= "Out of service";
    this.chooseloc= "Location Marker";
  }
}
}